name: Shopping Cart CI/CD

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SourceCode
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build Project
        run: mvn clean package -DskipTests
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ankitfs/productmgmtapi .
      - name: Publish Image to Docker Hub
        run: docker push ankitfs/productmgmtapi:latest
  deloy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from DockerHub
        run: docker pull ankitfs/productmgmtapi:latest
      - name: Delete Old Container
        run: docker rm -f shopping-cart-api
      - name: Run Docker Container
        run: docker run -e SPRING_DATASOURCE_URL=jdbc:postgresql://db-private-test.cjs2w0eikr03.ap-south-1.rds.amazonaws.com:5432/shoppingcart -e SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver -e SPRING_DATASOURCE_USERNAME=dev_master -e SPRING_DATASOURCE_PASSWORD=Postgres40 --name shoppingcart-backend -p 8080:8080 shoppingcartbackend:latest